Completed typescript-carousel exercise
techmatlock/c0524-code-solutions pull request #70
Opened 2024-06-12 20:42 UTC by techmatlock

![Recording 2024-06-11 at 20 08 09](https://github.com/techmatlock/c0524-code-solutions/assets/2618095/8b0b354f-c6b6-4f00-9262-e2ba0cea86a1)

2024-06-12 21:32 UTC, brandon-moy requested changes
Great start and looks like it does work 👍 I left a couple of comments about some parts that confuse me. If you can provide me with an answer in a comment of why its needed then I will approve. You just need to answer about:

- The `itemId` check on line 98 and 99
- the `querySelector` on line 118

2024-06-12 21:32 UTC, brandon-moy commented on typescript-carousel/main.ts
> +
I would personally make line 96 `if(!$eventTarget.match('.dot')) return`. This way if it doesn't match, we just exit the function. It makes it more understand that we only want to continue if the user clicked a dot.

On line 98 and 99, isn't this doing the same thing? You check is `itemId` is strictly equal to null and then you check if `itemId` is truthy. Couldn't you just check if _not_ `itemId` on line 98?

2024-06-12 21:32 UTC, brandon-moy commented on typescript-carousel/main.ts
> +  $allDots.forEach((dot) => {
Do you need this query here on line 118? Aren't you already querying for all of your dots on line 8?

2024-06-12 21:34 UTC, techmatlock commented on typescript-carousel/main.ts
> +  $allDots.forEach((dot) => {
Yeah but I thought I needed to query the page again anytime I loop through elements again with the foreach?

2024-06-12 21:41 UTC, techmatlock commented on typescript-carousel/main.ts
> +
I didn't think about that guard clause but I like that much better now that you mentioned it.

So with your question, should the revised code be?

`if (!itemId) return;
  if (itemId) {
    $currentImage.src = images[+itemId];
  }`

2024-06-12 23:10 UTC, brandon-moy commented on typescript-carousel/main.ts
> +
My question for this is, don't they check the same thing?
`if (!itemId) return` checks if `itemId` is falsy, and if it is we exit the function.
`if (itemId) { $currentImage.src = images[+itemId] }` checks if `itemId` is truthy, and if it is we run the code.

Why do we need to check if it is truthy if we already verified that it isn't falsy? 🤔

2024-06-12 23:12 UTC, brandon-moy commented on typescript-carousel/main.ts
> +  $allDots.forEach((dot) => {
We shouldn't need to query it again because we're not adding or removing any of the dots. Since the dots aren't changing the query we made at the beginning would still be the correct dots.

2024-06-12 23:54 UTC, techmatlock commented on typescript-carousel/main.ts
> +
@brandon-moy Oh I see the logic now.  The second if truthy condition would never get executed anyways cause the  if itemID is falsy (!itemId) would exit the function.  Thanks.

2024-06-12 23:58 UTC, techmatlock commented on typescript-carousel/main.ts
> +  $allDots.forEach((dot) => {
@brandon-moy Ah ok.  I was overthinking it.  Thanks.

2024-06-13 00:04 UTC, brandon-moy commented on typescript-carousel/main.ts
> +  $allDots.forEach((dot) => {
Hopefully this doesn't confuse you more but maybe the idea that `querySelectorAll` returns a _static_ NodeList may have caused the overthinking. Since your `forEach` is changing each dot back to the not active one and only adding the active look to the one that matches your check, it doesn't matter if the NodeList isn't "up to date" with any changes you had made.

2024-06-13 00:05 UTC, brandon-moy approved these changes
Great job, approved! 👍 

Left a comment for you about what may have been why you were overthinking it and a little more explanation about why you wouldn't need that extra query, hopefully it isn't more confusing!

2024-06-13 00:07 UTC, techmatlock commented on typescript-carousel/main.ts
> +  $allDots.forEach((dot) => {
@brandon-moy Ah, I like that explanation.  That was helpful thank you!

2024-06-13 00:08 UTC, merged