Completed typescript-promises exercise
techmatlock/c0524-code-solutions pull request #72
Opened 2024-06-12 23:49 UTC by techmatlock

![Screenshot 2024-06-12 at 4 48 52 PM](https://github.com/techmatlock/c0524-code-solutions/assets/2618095/6b17588e-989a-472b-aa73-c469b42d49a8)

2024-06-12 23:51 UTC, brandon-moy requested changes
Right code, wrong file!

2024-06-12 23:51 UTC, brandon-moy commented on typescript-promises/take-a-chance.ts
> +  .catch((error) => console.log(error.message));
This should be in your `main.ts` file and you run `tsx main.ts` instead of being in your `take-a-chance.ts` file.

2024-06-13 00:12 UTC, techmatlock commented on typescript-promises/take-a-chance.ts
> +  .catch((error) => console.log(error.message));
Ok, should be good now.  Thanks.

2024-06-13 04:25 UTC, brandon-moy approved these changes
Approved! 👍

2024-06-13 18:28 UTC, merged